### ISSUE TITLE
Uncaught Error: "Cannot read property 'allowFontScaling' of undefined" with react-native 0.70.0

### ISSUE THREAD

**Issue by marvanov** [djchie/react-native-star-rating#113]
Hi
react-native 0.68.2 - works,
react-native 0.70.0 - not works,

Uncaught Error: "Cannot read property 'allowFontScaling' of undefined"

My using:
```
import StarRating from 'react-native-star-rating'
<StarRating disabled={true} maxStars={5} rating={reading[0] ? reading[0]._raw.user_rate : 0} fullStarColor={colors.t[15]} starSize={15} containerStyle={styles.stars} />
```

What can I do about it? Thanks!

**Comment by MohamedAhmed122** [comment]
I have the same issue, after upgrading to react-native v0.69.5
@djchie  any clue how to resolve this issue?

**Comment by cauyyl** [comment]
rn 69.2 face the same issue

**Comment by andreav** [comment]
Same here on  0.70.4
Did someone find a solution?

**Comment by NewSky54** [comment]
Same issue on 0.70.5.

**Comment by moulie415** [comment]
You need to use patch-package to fix this one see my comment on the duplicate issue https://github.com/djchie/react-native-star-rating/issues/118#issuecomment-1379488952
