### ISSUE TITLE
0.24.1 seems to be not compatible with this?

### ISSUE THREAD

**Issue by jojonarte** [djchie/react-native-star-rating#12]
The package react-native@0.24.1 does not satisfy its siblings' peerDependencies requirements!

**Comment by ramose** [comment]
Have the same issue.

**Comment by robtg4** [comment]
Same issue

**Comment by xxn520** [comment]
same issue

**Comment by jojonarte** [comment]
I wonder where this issue comes from exactly

**Comment by jaimecorrea** [comment]
Same, any updates?

**Comment by djchie** [comment]
Sorry about the delay you guys, I'll get a fix in by this weekend
