### ISSUE TITLE
Use our own images

### ISSUE THREAD

**Issue by luisfuertes** [djchie/react-native-star-rating#21]
I want use my resources icon. 

It is posible? 

Example: `fullStar={require('../../../Resources/star.png')}`

**Comment by zachrnolan** [comment]
Would love to see something like this implemented.

**Comment by derdav3** [comment]
+1

**Comment by michelsch92** [comment]
+1

**Comment by Maydar** [comment]
+

**Comment by djchie** [comment]
This will be in the next release thanks to @rocwangv !

**Comment by ttibau** [comment]
has this been implemented?
Edit: Yes! 👍
