### ISSUE TITLE
Half Star Rating

### ISSUE THREAD

**Issue by seque1990** [djchie/react-native-star-rating#24]
I see in the documentation that it is possible to display a half-star rating (i.e. 3.5/5), however I was wondering if there is a way to rate with half-star, and if so, how do you make this possible? 

We've implemented the component and it's working nicely, but we haven't been able to rate with a half-star rating so far. Thank you very much for any help.

**Comment by djchie** [comment]
Selecting half stars will be in the next release thanks to @dejakob !
