### ISSUE TITLE
Excuse me.

### ISSUE THREAD

**Issue by pheromone** [djchie/react-native-star-rating#42]
打扰一下,我可以滑动打星星吗?还有现在只能显示半颗星星,但是不能点击出来半颗星星.
Excuse me, can I slide the stars? And now I can show only half a star, but not half a star

**Comment by djchie** [comment]
Right now, this does not support the sliding stars feature. If you'd like to make a PR for the feature, I'll be glad to review it and merge it if it checks out. Also, selecting half stars will be in the next release thanks to @dejakob !
