### ISSUE TITLE
Half star color not being applied

### ISSUE THREAD

**Issue by developer239** [djchie/react-native-star-rating#50]
I set star color. I set empty star color. Half star color still has the default look though. Is it possible to fix that? :)

**Comment by djchie** [comment]
@developer239, not sure what you mean by this. Could you provide a more detailed example?

**Comment by developer239** [comment]
You can set a color of a full start or of an empty star. I don't think it is possible to set a color of a half-full star.

**Comment by djchie** [comment]
@developer239 Gotcha, I'll go ahead and add that into the next update. Thanks for the suggestion!

**Comment by MattMangoni** [comment]
fullStarColor is not working either, but the old "starColor" is.
If you want to have the same color for everything, you need to combine emptyStarColor (the only one that's working atm) and starColor :)

**Comment by djchie** [comment]
@MattMangoni, what version of the component are you using? I just released an update for `1.0.9`.
