### ISSUE TITLE
Set component's size and spacing

### ISSUE THREAD

**Issue by gantonioid** [djchie/react-native-star-rating#53]
Is it possible to set the size of the component? the stars render too small and close to each other, even in a tablet.

**Comment by zygama** [comment]
how i do it -> put the stars in a view which has style with width defined (it will stick stars to the maximum without covering each others to be as near as possible from the width u declared), and modify starSize to the value u want.
do some test its quite simple :)

**Comment by djchie** [comment]
I'll be making an update to `1.0.9` to add a `containerStyle` which should give you more flexibility to achieve this.
