### ISSUE TITLE
Can I turn off `activeOpacity` for individual star? 

### ISSUE THREAD

**Issue by jack2684** [djchie/react-native-star-rating#59]
I have a star view that doesn't expect any rating action, where I only need the star display feature.

**Comment by djchie** [comment]
This isn't a typical use case of the component so I can't currently think of an efficient way of implementing this. Would adding an `activeOpacity` prop to the star rating component help even though you'd be modifying all the stars?

**Comment by djchie** [comment]
@jack2684 In an upcoming update, you will now be able to add an `activeOpacity`.
