### ISSUE TITLE
Unrecognized font family 'FontAwesome'

### ISSUE THREAD

**Issue by LiuXingQiPan** [djchie/react-native-star-rating#6]

**Comment by LiuXingQiPan** [comment]
Sorry,it's my fault.

**Comment by djchie** [comment]
No worries.

**Comment by ajoshdee** [comment]
I'm having the same issue, how to solve this?

**Comment by LiuXingQiPan** [comment]
Sorry, it's long time ago and I has forgotten how to solve this. And now, maybe you has solved it. I advise you could read the readme.Very sorry to see this at now.

**Comment by MudassirAziz** [comment]
readme file is not opening ... can any one explain how to resolve the error "Unrecognized font family 'FontAwesome'"?
