### ISSUE TITLE
StarRating.js not parsing

### ISSUE THREAD

**Issue by haneyman** [djchie/react-native-star-rating#64]
Hello, for some reason StarRating.js is not parsing during compile in a standard React projet.  Any ideas?
Compiler message:
/node_modules/react-native-star-rating/StarRating.js
Module parse failed: Unexpected token (121:8)
You may need an appropriate loader to handle this file type.
| 
|       const starButtonElement = (
|         <StarButton
|           activeOpacity={0.20}
|           buttonStyle={buttonStyle}
 @ ./node_modules/react-native-star-rating/index.js 2:0-38 4:15-25
 @ ./components/Stars.js
 @ ./app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app

**Comment by djchie** [comment]
@haneyman Not too sure what you're running into. Are you still running into this issue?

**Comment by haneyman** [comment]
No longer an issue thanks.
