### ISSUE TITLE
Star icon not displaying

### ISSUE THREAD

**Issue by DurgaManickam** [djchie/react-native-star-rating#7]
**Star icon not displaying instead blank screen gets displayed".
Example Code as follows:

import React from 'react-native';
var {
  AppRegistry,
  Component, 
  View,
} = React;

import StarRating from 'react-native-star-rating';

class CustomStarExample extends Component {
 
  constructor(props) {
    super(props);
    this.state = {
      starCount: 2.5
    };
  }
 
  onStarRatingPress(rating) {
    this.setState({
      starCount: rating
    });
  }
 
  render() {
    return (
    <StarRating 
        disabled={false}
        emptyStar={'android-star-outline'}
        fullStar={'android-star'}
        halfStar={'android-star-half'}
        iconSet={'Ionicons'}
        maxStars={5}
        rating={this.state.starCount}
        selectedStar={(rating) => this.onStarRatingPress(rating)}
        starColor={'yellow'} 
      />
    );
  }
}
AppRegistry.registerComponent('AbcProject', () => CustomStarExample);

**Comment by djchie** [comment]
Did you set up react-native-vector-icons for your project?

**Comment by DurgaManickam** [comment]
Its my fault . I included react-native-vector-icons but failed to do ** rnpm link**

**Comment by DurgaManickam** [comment]
now its working

**Comment by djchie** [comment]
No worries. Glad it's working!
