### ISSUE TITLE
Support for different Icons

### ISSUE THREAD

**Issue by abranhe** [djchie/react-native-star-rating#81]
It would be amazing to have the posiblitity to set different icons if the if developer wants to do so, at least up to five. Something like this:

<img src="https://user-images.githubusercontent.com/21347264/54480799-5b936980-4803-11e9-9f57-e4ce4e069e91.jpg" width="50%">

```js
import StarRating from 'react-native-star-rating';

class DifferentIcons extends Component {

  constructor(props) {
    super(props);
    this.state = {
      starCount: 5
    };
  }

  onStarRatingPress(rating) {
    this.setState({
      starCount: rating
    });
  }

  render() {
    return (
      <StarRating
        disabled={false}
        maxStars={5}
		starOne={'$'}
		starTwo={'$$'}
		starThree={'$$$'}
		starFour={'$$$$'}
		starFive={'$$$$$'}
        rating={this.state.starCount}
        selectedStar={(rating) => this.onStarRatingPress(rating)}
      />
    );
  }
}

export default DifferentIcons;
```

**Comment by EricWiener** [comment]
I created a fork that is able to do this: https://github.com/EricWiener/react-native-star-rating. I'm not going to pull since I don't believe this project is maintained.
